### ISSUE TITLE
Cannot share in SWAN

### ISSUE THREAD

**Issue by michzimny** [up2university/kuboxed#36]
At https://swan.test.up2university.eu/user/up001002/projects
when I click "Share" on a project, nothing happens.

At https://swan.test.up2university.eu/user/up001002/projects/test
when I click the sharing icon (top right), nothing happens.

JS console just says "Getting CERNBox auth token" after such clicks.

By the way, JS console says "TypeError: input_data is undefined" when loading either of these pages. I don't know if it's related.

**Comment by diocas** [comment]
A fix is coming this week. I was releasing last week as I mentioned in a previous email, but I've decided to couple another update (CERN only). I'll let you know as soon as released.

**Comment by diocas** [comment]
This should be solved with the latest images I sent you. Can you confirm?

**Comment by michzimny** [comment]
The problem still exists as described above.

Try here: https://swan.test.up2university.eu/

My images are:
* gitlab-registry.cern.ch/swan/docker-images/jupyterhub:v1.3
* gitlab-registry.cern.ch/sciencebox/up2u/swan-systemuser:v1.1

**Comment by diocas** [comment]
I cannot reproduce, but I think I know what it is. Can you try opening CERNBox in a new tab and try again?

**Comment by michzimny** [comment]
Ok, then it works. So, for users, a message should probably pop up and explain that they should have CERNBox tab opened.

**Comment by diocas** [comment]
The problem is the SSO that gets stuck waiting for user intervention before entering CERNBox.
I'll try to add a pop up that will show the login page to the users.
